### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#347]
**dg0yt reported on Sourceforge [[tickets:#347](https://sourceforge.net/p/oorienteering/tickets/347)]:**

The manual needs updating.

Collected by @Abbe98:

 - [X] Wiki icons missing (#311) (@dg0yt)
 - [X] FAQ needs update (updated from SF wiki -- @dg0yt)
 - [X] Update shortcut keys (#458)
 - [X] Map parts has no documentation (OpenOrienteering/mapper-manual#12)
   - [X] `map_menu.md` is missing map parts items
 - [X] `view_menu.md` is missing tag editor item (@wanacode)
 - [X] Tag editor has no documentation (needs more work -- @wanacode)
 - [ ] ~~Import has no documentation~~ (moved to #583)
 - [ ] ~~Missing docs for some tools?~~ (moved to #583)
 - [X] Update `georeferencing.md` (screenshot updated -- @dg0yt)
 - [ ] ~~Drawing tools "cheat sheet" (#160)~~ (moved to #583)
 - [X] Update screenshots (@dg0yt)

**Comment by Abbe98** [comment]
Trying to cover whats needs to be done:

 - [ ] Wiki icons missing #311
 - [ ] FAQ needs update
 - [ ] Update shortcut keys #458
 - [ ] `map_menu.md` is missing map parts items
 - [ ] `view_menu.md` is missing tag editor item
 - [ ] Tag editor has no documentation
 - [ ] Import has no documentation
 - [ ] Missing docs for some tools?
 - [ ] Map parts has no documentation
 - [ ] Update `georeferencing.md`

Additional:

 - Update screenshots(some differs)

This is just what I found after a quick read-through.

**Comment by dg0yt** [comment]
#347 is not directly related to the source, but to the manual's copy in the user wiki on sourceforge. I have not found yet a similar solution on Github which facilitates user contributions.
- GH wikis use a slightly different syntax for linking pages, and it is non-trivial to add/update pictures. These issues are show-stoppers.
- The manual might get a separate repository, with a different set of privileged accounts. On the other hand, contributions can be handled easily with pull requests.
- It might even be possible to have that separate repository published via jekyll. On the other hand I'm thinking about publishing updated manuals to the gh-pages branch of the mapper repository. This could be a simple optional build rule. I would publish the API documentation the same way.
- For generating HTML pages from markdown markup. I need to run the manual through Doxygen, not Jekyll. Doxygen is easy to compile during the build process, while Jekyll pulls a lot of dependencies. I already do some markdown preprocession in CMake scripts, so minor syntax changes can be handled.

**Comment by Abbe98** [comment]
I believe using Jekyll in a separate repo would be the best solution, with Github Pages the repo it self does no need to contain all dependencies or any Ruby code. That would allow contributions pretty easy.

It would be easy to maintain as you just has to edit basic MD files, assets/templates is stored in a separate directory. Doxygen could also just pull the MD files from the posts dir, the the actual Jekyll setup would not be a issue in any way.

One thing that might be a issue is that title, and other variables in Jekyll is inline at the top of the file,  Doxygen would need to be  able to handle this.

I could set this up if needed with design+Jekyll but the build process/Doxygen I have not much experience with...

**Comment by dg0yt** [comment]
I already have a copy of the docs in my personal repository, https://github.com/dg0yt/dg0yt.github.io. The "frontmatter" will not be an issue. But we need to decide on which file extension to use in the sources. This affects editing and linking. The generated files will use ".html".
- .md: Github will know that this is Markdow, and present it nicely in the repository. However, links to other files won't work very nice.
  - If you link to .md, it works in the repository but not in the pages from Jekyll. (For doxygen I could work around this limitation by another string substitution.)
  - If you link to .html, it will play well with Jekyll and doxygen, but links won't work in the repository.
  - If you link to the basename (without extension), it works in Jekyll, but doesn't work in the repository.
- .html: Github doesn't recognize that this is a Markdown file and thus doesn't display it as pretty. So links don't work in the repostitory because they are not rendered. In Jekyll and doxygen, .html links are fine, of course.

Maybe we could ignore Jekyll and just work with .md Markdown files in the repository. Fancy design is not so relevant, the Assistant app which comes with member supports only very basic markup.

.md file with some links: https://github.com/dg0yt/dg0yt.github.io/blob/master/index.md / http://dg0yt.github.io/

.html file: https://github.com/dg0yt/dg0yt.github.io/blob/master/toolbars.html / http://dg0yt.github.io/toolbars.html

**Comment by Abbe98** [comment]
Your example with markdown works fine for me in the browser as long as the link is relative(https://dg0yt.github.io). So markdown should be fine.

**Comment by dg0yt** [comment]
I found a workaround: in the page template, I replace 
```
    {{ content }}
```
by
```
    {{ content  | replace:'.md"','.html"' }}
```

So you can .md links in the repository, but get .html links in the published page. There shouldn't be too many false positives matching '.md"'.

**Comment by Abbe98** [comment]
If any I guess those could be escaped(or HTML encoded).

**Comment by dg0yt** [comment]
The new Mapper manual repository is now online at http://openorienteering.github.io/mapper-manual/ and ready for contributions at https://github.com/OpenOrienteering/mapper-manual. You may submit pull requests or ask to be added as a collaborator for this repository.

I'm quite happy how well this works  with editing and publishing, and with shuffling around the contents by means of ```git subtree```. I will try to look into getting full HTML support in the local help browser without deploying Qt's deprecated Webkit.

**Comment by dg0yt** [comment]
From my point of view, the outstanding documentation issues no longer block the release of 0.6.0. Thanks for the all contributed work - keep going on...

**Comment by dg0yt** [comment]
To test what is possible with Bootstrap and jQuery:

http://dg0yt.github.io/mapper-manual-dynamic/pages/file_menu.html

**Comment by Abbe98** [comment]
There is no need to load Bootstrap or jQuery for such as simple thing. A few lines of javascript to switch values in a table on button click...

The fonts look much nicer but we could just edit the existing CSS bit not a fan of the wider view.

**Comment by Abbe98** [comment]
Also because the script tag is placed before loading jQuery an error is always thrown.

**Comment by dg0yt** [comment]
I'm not a Javascript expert. Due to all the past browser incompatibilities and security issues, I didn't use it much before 2015...

Bootstrap and jQuery are part of the openorienteering web site anyway, and I didn't really try to polish or minimize. This is is a proof-of-concept and not meant for direct merging. The changed font is a nice side effect, the change of margins/the wider view is unintended. Looking at the HTML structure, there is some potential for cleanup.

**Comment by Abbe98** [comment]
Okey, cleaning up that HTML is on my list of possible contributions, it's possible that I get it done during the holidays.
